name: 'Windows v1.0.2'

on:
  workflow_call:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string

jobs:
  build:
    name: Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Package amd64
        run: |
          mkdir -p temp
          cp bin/jwlIntegrator-amd64.exe temp/jwlIntegrator.exe
          zip -j temp/jwlIntegrator_windows_amd64.zip temp/jwlIntegrator.exe lib/sqlite3_64.dll lib/unzip.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: jwlIntegrator_windows_amd64.zip
          path: temp/jwlIntegrator_windows_amd64.zip

      - name: Package arm64
        run: |
          rm -rf temp/*
          mkdir -p temp
          cp bin/jwlIntegrator-arm64.exe temp/jwlIntegrator.exe
          cp lib/sqlite3_ARM.dll temp/sqlite3_64.dll
          zip -j temp/jwlIntegrator_windows_arm64.zip temp/jwlIntegrator.exe temp/sqlite3_64.dll lib/unzip.exe

      - name: Upload Android artifact
        uses: actions/upload-artifact@v7
        with:
          name: jwlIntegrator_android.sh
          path: bin/jwlIntegrator_installer.sh